name: Run Frame1 Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "48 6 * * *"  # Runs at 12:18 PM IST daily


jobs:
  frame1-test-run:
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: "frame1"
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
