name: Run Frame1 Tests - Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "15 12 * * 1"  # 5:45 PM IST on Mondays

jobs:
  frame1-test-run:
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: 'FRAME1'
      tag-filter: 'WEEKLY'
      result-file: 'results-0-1.chrome.xml'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
