name: Run Tests - FRAME1 Daily & CK Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"    # 3:30 PM IST
    - cron: "10 10 * * *"   # 3:40 PM IST

jobs:
  run-daily-frame1-tests:
    if: github.event.schedule == '0 10 * * *'
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: 'FRAME1'
      tag-filter: 'DAILY'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}

  run-weekly-ck-tests:
    if: github.event.schedule == '10 10 * * *'
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: 'CK'
      tag-filter: 'WEEKLY'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
