name: Run Frame3 Tests - Daily and Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "18 9 * * *"     # 2:48 PM IST → 09:18 AM UTC
    - cron: "30 9 * * 4"     # 3:00 PM IST Thursday → 09:30 AM UTC Thursday

jobs:
  frame3-test-run:
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: 'FRAME3'
      tag-filter: 'DAILY|WEEKLY'
      result-file: 'results-frame3.xml'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
