name: Run Frame Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "53 7 * * *"  # Runs at 1:23 PM IST daily

jobs:
  frame-test-run:
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: "\\[FRAME\\]"
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
