name: Run FRAME Tests - Daily

on:
  schedule:
    - cron: "20 9 * * *"  
  workflow_dispatch:

jobs:
  frame1-test-run:
    uses: ./.github/workflows/test-runner.yml
    with:
      test-path: './test/specs/daily-regression-suite/frame.tests.ts'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
