name: Run Frame1 Tests - Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "20 20 * * *"  # 2:00 AM IST = 20:30 UTC (IST is UTC+5:30)

jobs:
  frame1-test-run:
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: 'FRAME1'
      tag-filter: 'DAILY'
      result-file: 'results-0-1.chrome.xml'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
