name: Run Frame1 Tests - Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "21 21 * * 2"  # 3:00 AM IST = 21:30 UTC, every Tuesday
jobs:
  frame1-test-run:
    if: github.ref == 'refs/heads/qa'  # ✅ ensures job runs only on 'qa'
    uses: ./.github/workflows/test-runner.yml
    with:
      scenario-tags: 'FRAME1'
      tag-filter: 'WEEKLY'
    secrets:
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_API_TOKEN: ${{ secrets.TESTRAIL_API_TOKEN }}
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
      TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
