name: Execute Tests Per Tag in Excel Priority Order

on:
  workflow_dispatch:
  push:
    paths:
      - 'tag-priority.xlsx'

jobs:
  extract-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Install xlsx
        run: npm install xlsx

      - name: Read Excel and extract tags
        id: set-matrix
        run: |
          node -e "
          const fs = require('fs');
          const xlsx = require('xlsx');
          const sheet = xlsx.readFile('./tag-priority.xlsx').Sheets.Sheet1;
          const rows = xlsx.utils.sheet_to_json(sheet, { header: 1 }).slice(1);
          const tags = rows.map(row => row[0]).filter(Boolean);
          const matrix = tags.map(tag => {
            const formatted = tag.startsWith('[') ? tag : \`[\${tag}]\`;
            const escaped = formatted.replace(/\[/g, '\\\\[').replace(/\]/g, '\\\\]');
            return { raw: formatted, escaped };
          });
          fs.writeFileSync('matrix.json', JSON.stringify({ include: matrix }, null, 2));
          console.log('::set-output name=matrix::' + JSON.stringify({ include: matrix }));
          "

  run-tests:
    needs: extract-tags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.extract-tags.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install xlsx

      - name: Run tests for tag ${{ matrix.raw }}
        run: |
          echo "Running tests for tag: ${{ matrix.raw }}"
          npx wdio run ./wdio.conf.ts --mochaOpts.grep="${{ matrix.escaped }}"
