name: Execute Tests Based on Excel Tags

on:
  workflow_dispatch:
  push:
    paths:
      - 'tag-priority.xlsx'

jobs:
  run-priority-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install tsx xlsx --save-dev

      - name: Read tags from Excel
        id: extract_tags
        run: |
          node -e "
          const fs = require('fs');
          const xlsx = require('xlsx');
          const workbook = xlsx.readFile('./tag-priority.xlsx');  // Path to the Excel file
          const sheet = workbook.Sheets[workbook.SheetNames[0]];
          const data = xlsx.utils.sheet_to_json(sheet, { header: 1 });
          
          // Extract tags from the first column
          const tags = data.map(row => row[0]).filter(tag => tag);
          
          // Save tags to file for use in the workflow
          fs.writeFileSync('tags.txt', tags.join('\n'));
          "

      - name: Read tags from file
        id: tags_var
        run: |
          echo "tags=$(cat tags.txt)" >> $GITHUB_ENV
          echo "Tags read from Excel: ${{ env.tags }}"

      - name: Run tests for tags
        run: | 
            TAGS=$(cat tags.txt | sed 's/\[/\\[/g; s/\]/\\]/g')  # Escape brackets
            echo "Running test cases matching Mocha tag: $TAGS"
            npx wdio run ./wdio.conf.ts --mochaOpts.grep="$TAGS"
          