name: Execute Tests Based on Excel Tag

on:
  workflow_dispatch:
  push:
    paths:
      - 'tag-priority.xlsx'

jobs:
  run-priority-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install tsx xlsx --save-dev

      - name: Read top tag from Excel
        id: extract_tag
        run: |
          node -e "
          const fs = require('fs');
          const xlsx = require('xlsx');
          const workbook = xlsx.readFile('./tag-priority.xlsx');  // Path to the Excel file
          const sheet = workbook.Sheets[workbook.SheetNames[0]];
          const data = xlsx.utils.sheet_to_json(sheet, { header: 1 });
          const tag = data[0]?.[0] || '';  // Reading first column from the first row
          fs.writeFileSync('tag.txt', tag.trim());
          "

      - name: Read tag for Mocha grep
        id: tag_var
        run: echo "tag=$(cat tag.txt)" >> $GITHUB_OUTPUT

      - name: Run tests for top tag
        run: |
          echo "Running test cases matching Mocha tag: '${{ steps.tag_var.outputs.tag }}'"
          npx wdio run ./wdio.conf.ts --mochaOpts.grep="${{ steps.tag_var.outputs.tag }}"
