name: Execute Tests Based on Excel Tags

on:
  workflow_dispatch:
  push:
    paths:
      - 'tag-priority.xlsx'

jobs:
  run-priority-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install xlsx --save-dev

      - name: Extract and format tags from Excel
        id: extract_tags
        run: |
          node -e "
          const fs = require('fs');
          const xlsx = require('xlsx');
          const workbook = xlsx.readFile('./tag-priority.xlsx');
          const sheet = workbook.Sheets[workbook.SheetNames[0]];
          const data = xlsx.utils.sheet_to_json(sheet, { header: 'A', defval: '' });
          
          // Process tags: ensure brackets, escape for regex, and remove duplicates
          const tags = [];
          for (let i = 1; i <= Object.keys(data).length; i++) {
            const cell = data[i]?.['A']?.trim();
            if (cell) {
              // Add brackets if missing and escape for regex
              const formattedTag = cell.startsWith('[') ? cell : `[${cell}]`;
              const escapedTag = formattedTag.replace(/\[/g, '\\[').replace(/\]/g, '\\]');
              if (!tags.includes(escapedTag)) {
                tags.push(escapedTag);
              }
            }
          }
          
          // Save as environment variable and file
          const tagsStr = tags.join(',');
          fs.writeFileSync('tags.txt', tagsStr);
          console.log('Extracted tags:', tagsStr);
          console.log(`::set-output name=tags::${tagsStr}`);
          "

      - name: Run WDIO tests with extracted tags
        run: |
          # Read tags and run tests (already escaped in extraction step)
          TAGS=$(cat tags.txt)
          if [ -z "$TAGS" ]; then
            echo "No tags found in Excel file!"
            exit 1
          fi
          
          echo "Running tests for tags: $TAGS"
          npx wdio run ./wdio.conf.ts --mochaOpts.grep="$TAGS"