name: Run Tag Test

on:
  workflow_call:
    inputs:
      scenario-tags:
        required: true
        type: string

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install xlsx --save-dev

      - name: Run tests for ${{ inputs.scenario-tags }}
        run: |
          TAG="${{ inputs.scenario-tags }}"
          ESCAPED=$(echo "$TAG" | sed 's/\[/\\\[/g; s/\]/\\\]/g')
          echo "Executing for $TAG -> escaped: $ESCAPED"
          npx wdio run ./wdio.conf.ts --mochaOpts.grep="$ESCAPED"
