name: WebDriverIO Dedicated Spec Executor

on:
  workflow_call:
    inputs:
      test-path:
        required: true
        type: string
    secrets:
      TESTRAIL_USERNAME:
        required: true
      TESTRAIL_API_TOKEN:
        required: true
      TESTRAIL_HOST:
        required: true
      TESTRAIL_PROJECT_ID:
        required: true
      TESTRAIL_SUITE_ID:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set ENV variables
        run: |
          echo "SCHEDULED_RUN=true" >> $GITHUB_ENV
          echo "TESTRAIL_HOST=${{ secrets.TESTRAIL_HOST }}" >> $GITHUB_ENV
          echo "TESTRAIL_USERNAME=${{ secrets.TESTRAIL_USERNAME }}" >> $GITHUB_ENV
          echo "TESTRAIL_API_TOKEN=${{ secrets.TESTRAIL_API_TOKEN }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          echo "Running spec: ${{ inputs.test-path }}"
          npx wdio run wdio.conf.ts --spec ${{ inputs.test-path }}
